// Keys produced with utils/parse_unique_pos_tags.ts
// Tags defined: https://github.com/languagetool-org/languagetool/blob/master/languagetool-language-modules/fr/src/main/resources/org/languagetool/resource/fr/tagset.txt

export default {
  "1": "première personne",
  "2": "deuxième personne",
  "3": "troisième personne",
  A: "adverbe",
  avoir: "avoir",
  C: "conjonction",
  con: "conditionnel",
  coor: "de coordination",
  D: "déterminant",
  dem: "démonstratif",
  e: "épicène",
  etre: "être",
  excl: "d’exclamation",
  f: "féminin",
  fin: "finale",
  futu: "futur",
  I: "interjection",
  imp: "imperative",
  impa: "imparfait",
  ind: "indicatif",
  inf: "infinitif",
  inte: "interrogatif",
  J: "adjectif",
  K: "nombre cardinal (mot)",
  M: "ponctuation",
  m: "masculin",
  N: "nom commun",
  nonfin: "non-finale",
  obj: "objet",
  O: "onomatopeia",
  P: "préposition",
  "P+D": "préposition + déterminant",
  "P+R": "préposition + pronom",
  p: "pluriel",
  pers: "personnel",
  ppa: "participe passé",
  ppr: "participe présent",
  pres: "présent",
  psim: "passé simple",
  R: "pronom",
  rel: "relatif",
  s: "singulier",
  sp: "singulier ou pluriel",
  sub: "subjonctif",
  subo: "de subordination",
  suj: "sujet",
  S: "sigle",
  T: "titre",
  V: "verbe",
  Y: "nombre cardinal (chiffre)",
  Z: "nom propre"
} as Record<string, string>;
